name: Build and Push Node.js Image

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ARN }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./nodejs
          push: true
          tags: |
            ${{ secrets.AWS_ECR_NODEJS }}:${{ github.event.release.tag_name }}
            ${{ secrets.AWS_ECR_NODEJS }}:latest
